### ISSUE TITLE
Link code references in low-level API docstrings

### ISSUE THREAD

**Issue by oubiwann** [clojang/clojang#14]
Right now the docstrings in the low-level API have the following issues:

* Some object names are just ``code`` text instead of being links to the documentation for that object
* Some linked code points to the javadocs, some to the low-level API docs
* parameters and return values are not discussed

These all need to be fixed:

* [ ] Ensure all ``code`` text points to the low-level documentation for the given namespace or function
* [ ] Ensure that the JInterface objects are referenced only when saying what is wrapped (and then, link to the javadocs)
* [ ] Ensure that docstrings have notes about the return value and the possible types for function arguments)

**Comment by yurrriq** [comment]
Any interest in adding Typed Clojure annotations?

**Comment by oubiwann** [comment]
Huh, that's a pretty interesting idea ... Codox will capture these and put them in the docs?

**Comment by oubiwann** [comment]
Ah:
 * https://github.com/weavejester/codox/issues/80
 * https://github.com/weavejester/codox/pull/82

Looks like development stalled ... maybe we could help give it a bump?

I think your idea's a great one -- if core.typed support lands in Codox, let's do it!

**Comment by yurrriq** [comment]
Sounds like a fun project if no one else picks it up first.

**Comment by oubiwann** [comment]
Alight, I got started on this tonight and pushed this branch up:
 * https://github.com/oubiwann/codox/tree/add-core.typed-support

I've put a bunch of stuff in place, including a new src in the example with some sample core.typed code. To run codox in this branch using the source code of that branch (with the core.typed changes) for both the project and the lein plugin, do the following:

* ``cd`` into ``examples`` and ``mkdir checkouts``
* ``cd`` into ``checkouts`` and ``ln -s ../../codox && ln -s ../../lein-codox``
* ``cd`` back into the ``examples`` directory and run codox with the "typed" protocol: ``lein with-profile +typed codox``

There are a few mysteries to me, still:
 * This issue is occurring for the generated docs: https://github.com/weavejester/codox/pull/82#issuecomment-72982070
 * In [this comment](https://github.com/weavejester/codox/pull/82#discussion_r24142557) and [this one](https://github.com/weavejester/codox/pull/82#issuecomment-72992631) @weavejester references an old state of the function and that the ``var->symbol`` function should be called. Not sure how that should be done yet

Soooo tired now; falling asleep at the laptop :sleeping: ...

**Comment by yurrriq** [comment]
Awesome! I've started add annotations to clojang. :smile:

**Comment by yurrriq** [comment]
In doing so, I think I caught a few typos in messaging btw. Now I'm falling asleep..

**Comment by oubiwann** [comment]
Nice -- core.typed is already helping us!

**Comment by yurrriq** [comment]
:smile: The annotations could definitely be cleaned up and could probably use some aliases. I'd never annotated a protocol before, so that was cool.

Also, I had some trouble annotating overloaded Java methods, namely `.exit` and `.send`. I left `XXX` notes.

**Comment by oubiwann** [comment]
We're making progress on the old core.typed branch in codox; the updated branch is currently in review:
 * https://github.com/weavejester/codox/pull/117

**Comment by yurrriq** [comment]
Awesome! I haven't taken a proper look at the code yet, but it sounds like you're figuring it out. Thanks to Ambrose, I was able to fix some unnecessarily limiting annotations too. :smile:

**Comment by oubiwann** [comment]
This will be done in the jiface, since the low-level API has moved there.
