### ISSUE TITLE
Epic: Create native Clojure core.async Erlang Ports Interface

### ISSUE THREAD

**Issue by oubiwann** [clojang/clojang#16]
This one's a biggie. 

Sadly, the JInterface library, as it stands, locks us into an old-school threading model and doesn't take advantage of Java's newest concurrency primitives.  Clojure's core.async provides an elegant Lisp interface to these (and more), and may be ideally suited for creating light-weight (non-OS) processes that can communicate with Erlang via the Erlang ports specification. 

This would be much easier if message parsing in JInterface is separated from communications (not sure if this is the case or not ... kind of doubt it), since that would mean we'd have to write less code.

This epic may depend upon the following yak (herds) to be shaved:
 * Create (or use) a Clojure library that implements basic actors on top of core.async
   * Qusar/Pulsar provide a core.async wrapper, but those libraries are way too much for what we need 
   * is it possible to only use part of them?
   * are there other libraries available which provide basic actor model abstractions on top of core.async?
   * if we need to write this in Clojure, it should go in its own project
 * Create (or use) a Clojure/Java for simply parsing and transforming "external" Erlang messages into Clojure data structures
   * we may be able to re-purpose JInterface for this, as long as we don't have to instantiate communication objects in order to do so ... 
   * if that's the case, we may want to re-implement the parsing functionality in Clojure
   * if we need to write this in Clojure, it should go in its own project

Once these questions have been answered, and the dependencies are met, we'll have a clear idea of the tasks necessary to actually code up this epic. At that point, this ticket description should be updated with the high-level tasks needed to develop this feature. Those should then  be created as tickets (and linked to the bullet list tasks). Each of those tickets should be broken down into actual tasks that can map to feature branches.

**Comment by oubiwann** [comment]
One of the first tasks we'll want to do is create a new home for the the current mid-level API, e.g. ``clojang.ji`` (as opposed to ``clojang.jinterface``). As a Clojang mid-level API namespace is converted from JInterface to core.async, we will move the old mid-level wrapper into ``clojang.ji`` so that it's still available, should anyone want to continue using it. The new implementation of the mid-level API (which will use whatever actor-model-wrapping-core.async we identify or create as well as whatever Erlang message-parsing library we decide upon) should stay as close as possible to the existing mid-level API as far as namespaces, function names, function arguments, and return values go.

**Comment by oubiwann** [comment]
I've managed to do some reading of the Java source code, and it looks like we *could* in fact using just the message-parsing bits and create a new, Clojure-native interface built on core.async.

At it's core, ``Mbox.receive`` uses ``OtpInputStream.read_any`` (via ``OtpMsg``) and ``OtpConnection.send`` uses ``OtpOutputStream.write*`` via ``AbstractConnection``. In short, lot of hard work is not only already done, but is available in a perfectly usable manner.

Phew!

**Comment by yurrriq** [comment]
Oh awesome! Are you gonna create a new project then for the bare bones `core.async`-based actor model?

**Comment by oubiwann** [comment]
I've gone back and forth on that several times -- part of Clojang? or a separate library?In some ways it seems so specific to Clojang (i.e., Clojure <-> Erlang interop). In other ways, possibly useful for others. Last night I did tons of re-reading on papers and source code I'd looked at before as well as new stuff I hadn't dug into yet (most of it actually pretty basic and really focused on the implementation details of Erlang's process model). After that, I did finally come to a decision -- the same one you have anticipated: creating a very minimal library in Clojure, built on core.async, that does the following:

 * as closely as possible, implements the Erlang process model

And does *not* do either of the following:

 * make assumptions about message structure or content
 * dictate (or create) the infrastructure necessary to support remoting, etc.

As such, this should be a general-purpose, low-level library for the JVM for anyone who is interested in building systems with functions that can communicate with each other.

For our purposes in Clojang, we would combine with it the message-parsing capabilities of JInterface (in/out streams) and communicate with ``epmd`` (our "framework" of choice). If all goes well, this should allow for Clojure applications to easily and seamlessly communicate with Erlang applications -- and do so at scale -- without being crippled by the overhead of one or more threads per function (for the cases when a function needs its own connection).

I need to do a little more reading before I can ask the right questions, but once I do, I hope I can talk @rvirding into being my tutor as I learn as much as possible about Erlang's process model and how to implement it in Clojure.

**Comment by oubiwann** [comment]
Alright, I've got a placeholder project for it here:
 * https://github.com/oubiwann/zhang

The name comes from [Zhang Heng](https://en.wikipedia.org/wiki/Zhang_Heng), who approximated π early in the first millennium (Han Dynasty). This is an obscure pun, since the Erlang process model could be, in some ways, interpreted as an approximation of the π-calculus ...

In addition to being a mathematician, Zhang Heng was also a poet, astronomer, and engineer -- a wonderful patron for a software project!

**Comment by yurrriq** [comment]
This sounds like a solid plan to me. I think there is definite potential for great utility in zhang outside of clojang's purposes, e.g. asynchronous/real-time web servers or something.

Also, great choice of name and justification. :smile:

**Comment by oubiwann** [comment]
Closing this ticket, since it will be done in Zhang.
