### ISSUE TITLE
Add core.async example to "Talking to Servers" examples

### ISSUE THREAD

**Issue by oubiwann** [clojang/clojang#18]
As came up in ticket #17, I'd like to add a core.async example to the "Talking to Servers" docs (see http://oubiwann.github.io/clojang/current/30-talking-to-servers.html).

In particular, the Clojure server example (second half of the page) needs to offer the same functionality as the LFE server example (top half of the page). @yurrriq has offered to provide some examples for this ... :+1:

**Comment by oubiwann** [comment]
See the example that @yurrriq (thanks, man!) pasted here:
 * https://github.com/oubiwann/clojang/issues/17#issuecomment-179440326

**Comment by oubiwann** [comment]
To put a finer point on what I'm trying to accomplish in the server example at the top of the Clojure section ... hrm, perhaps better to compare to the two LFE servers:

The quick-and dirty LFE server is just that: very simple, no safeguards -- of pedagogical use only. The quick-and-dirty Clojure server is a very close analog (amazingly so, thanks to core.match).

The full OTP LFE server is robust -- it's the kind of thing that couldn't handle [2 million concurrent connections on a FreeBSD box](https://blog.whatsapp.com/196/1-million-is-so-2011). Under the hood, the OTP gen_server shares a common heritage with the quick-and-dirty server, but it provides all sorts of additional plumbing (failover, timeouts, exception handling, the possibility for linking to supervision trees, etc.).

What I want for the main Clojure example is an analog to that. [Pulsar](http://docs.paralleluniverse.co/pulsar/) is one candidate. Perhaps [Vert.x](http://vertx.io/) is another option (they've got a [core.async](https://github.com/vert-x/vertx-examples/blob/master/src/raw/clojure/async/src/async/core.clj) example that looks interesting).

In many ways, this is an impractical request: OTP has message-handling all the way down to the metal. With JInterface, we're stuck in Thread-land. So maybe a futures-based framework would be most suitable? Regardless, what we need is not a networking-based framework per-se, but rather a framework built on messaging that could be used to *build* a networking framework. Hrm, Pulsar is sounding more and more like the best match...

**Comment by yurrriq** [comment]
Maybe manifold or funcool/promesa.

**Comment by oubiwann** [comment]
I'd considered two of funcool's promises libraries; I think Zach's a brilliant dude, so his stuff is always intriguing ... but I think I remember it being too slow compared to other abstraction libraries.

I'm honestly giving Okku a very serious look:
 * https://github.com/gaverhae/okku

Which, of course, brings me back to Pulsar. 

And .... I continue to be intrigued by the possibility of building an actor system on top of core.async. Here's a very short demo:
 * https://github.com/halgari/clojure-conj-2013-core.async-examples/blob/master/src/clojure_conj_talk/core.clj#L458

**Comment by oubiwann** [comment]
The problem I keep having with other actor systems is that they have their own implementation of epmd (Pulsar uses Galaxy and Okku uses Akka's thing). 

I don't think I can be satisfied until we've got native Erlang ports in Clojang (without using JInterface) that communicate with each other and epmd via core.async.

*sigh*

Need to think more about a second-best option ...

**Comment by oubiwann** [comment]
The [zhang project](https://github.com/clojang/zhang) will be tackling this issue, so I'm going to close this.

See https://github.com/clojang/zhang/issues/1
