### ISSUE TITLE
Annotate the low-level API

### ISSUE THREAD

**Issue by yurrriq** [clojang/clojang#22]
- [ ] `clojang.jinterface.erlang.atom`
- [ ] `clojang.jinterface.erlang.boolean`
- [ ] `clojang.jinterface.erlang.char`
- [ ] `clojang.jinterface.erlang.float`
- [ ] `clojang.jinterface.erlang.int`
- [ ] `clojang.jinterface.erlang.list`
- [ ] `clojang.jinterface.erlang.map`
- [ ] `clojang.jinterface.erlang.object`
- [ ] `clojang.jinterface.erlang.pid`
- [ ] `clojang.jinterface.erlang.port`
- [ ] `clojang.jinterface.erlang.string`
- [ ] `clojang.jinterface.erlang.tuple`
- [ ] `clojang.jinterface.erlang.types`
- [ ] `clojang.jinterface.erlang`
- [ ] `clojang.jinterface.otp.connection`
- [x] `clojang.jinterface.otp.messaging`
- [ ] `clojang.jinterface.otp.nodes` => [annotations/otp.nodes](https://github.com/yurrriq/clojang/tree/annotations/otp.nodes)
- [ ] `clojang.jinterface.otp`

**Comment by yurrriq** [comment]
Copied from yurrriq/clojang#1.

**Comment by yurrriq** [comment]
Related: #14

**Comment by oubiwann** [comment]
:sparkles: 
:smiley:

**Comment by oubiwann** [comment]
Hey, so what do you think about https://github.com/plumatic/schema instead of a full type system?

So far, what I'm reading makes a lot of sense ... without many of the issues of core.typed.

Interested in your thoughts ...

**Comment by yurrriq** [comment]
I've never used it in any "serious" capacity, but it seems sound enough. I think Typed Clojure could work quite well for us after a few more initial hurdles, but I'm not married to it.

**Comment by yurrriq** [comment]
@bhurlow, have you used schema? What do you think?

**Comment by bhurlow** [comment]
@yurrriq Prismatic schema? I don't use it

**Comment by bhurlow** [comment]
I'm more likely to use `pre` checks

**Comment by oubiwann** [comment]
So I decided to bail on core.types and just go with metadata annotation. Much simpler, and really the purpose was to be more developer friendly, so that devs know what's expected in each function call.

Also, note that the low-level API is now a stand-alone library: [jiface](https://github.com/clojang/jiface).

I'm going to close this ticket ...

**Comment by oubiwann** [comment]
See this ticket for the alternate path taken: https://github.com/clojang/jiface/issues/1

**Comment by yurrriq** [comment]
👍
