### ISSUE TITLE
Overhaul function returns

### ISSUE THREAD

**Issue by oubiwann** [clojang/clojang#9]
- [x] Functions from the mid-level API with `nil` (`void` in Java) return values should instead return `:ok`
- [x] Functions in the mid-level API that are sending data should return the sent data, not `nil` or `:ok`
-  Documentation needs to be updated with this change:
  - [x] Update README
  - [x] Update mid-level API user guide
  - [x] Update "Talking to Servers"
- Functions in the low-level API shouldn't be changed, but should be as close to the Java return values as possible

**Comment by yurrriq** [comment]
Sounds good to me.

**Comment by oubiwann** [comment]
Many of these have been updated. I'm sure there are outliers, but they can be fixed up as they are encountered.
